const KEY='calculator-workbench-v1';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{history:[],memory:0,mode:'basic',expr:'',result:'0'};
const tabs=[['basic','Basic'],['scientific','Scientific'],['converter','Converter'],['history','History']];
const $=s=>document.querySelector(s); const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));$('#saveState').textContent='Saved locally ✓'};
function renderTabs(){ $('#tabs').innerHTML=tabs.map(([id,t])=>`<button class="tab ${state.mode===id?'active':''}" data-mode="${id}">${t}</button>`).join(''); document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;save();render()}) }
function render(){renderTabs();$('#expression').textContent=state.expr||'0';$('#result').textContent=state.result||'0';const w=$('#workspace');if(state.mode==='basic')w.innerHTML=basic();else if(state.mode==='scientific')w.innerHTML=scientific();else if(state.mode==='converter')w.innerHTML=converter();else w.innerHTML=history();bind();}
function basic(){return `<div class="memory">${['MC','MR','M+','M-'].map(x=>`<button data-m="${x}">${x}</button>`).join('')}</div><div class="keypad">${['AC','⌫','%','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','±','='].map(x=>`<button class="key ${x==='AC'?'ac':''} ${['÷','×','−','+','%'].includes(x)?'op':''} ${x==='='?'equal':''}" data-k="${x}">${x}</button>`).join('')}</div><p class="notice">Includes parentheses, percentages, decimals and memory. Results are saved on this device.</p>`}
function scientific(){return `<div class="scientific">${['sin','cos','tan','asin','acos','atan','√','x²','xʸ','ln','log','π','e','(',')'].map(x=>`<button data-s="${x}">${x}</button>`).join('')}</div>${basic()}`}
function history(){return `<div class="panel card"><h2>Calculation History</h2><div class="history">${state.history.length?state.history.map((h,i)=>`<div class="history-item"><span>${escapeHtml(h.e)}</span><b>${escapeHtml(h.r)}</b></div>`).join(''):'<div class="empty">No calculations yet ✨</div>'}</div></div>`}
function converter(){return `<div class="panel card converter"><h2>Unit Converter</h2><div class="mode-row"><button class="mode-btn active" id="lengthMode">Length</button><button class="mode-btn" id="weightMode">Weight</button></div><div class="row"><input id="fromVal" class="input" type="number" value="1"><select id="fromUnit" class="select"></select></div><div class="row"><input id="toVal" class="input" readonly><select id="toUnit" class="select"></select></div><div class="convert-result" id="convResult">1</div><p class="notice">More converter categories can be added without a server.</p></div>`}
function bind(){document.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>key(b.dataset.k));document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>sci(b.dataset.s));document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>mem(b.dataset.m));if(state.mode==='converter')bindConverter()}
function key(k){if(k==='AC'){state.expr='';state.result='0'}else if(k==='⌫')state.expr=state.expr.slice(0,-1);else if(k==='='){calc()}else if(k==='±'){state.expr=state.expr.startsWith('-')?state.expr.slice(1):'-'+state.expr}else{const map={'×':'*','÷':'/','−':'-'};state.expr+=(map[k]??k)}state.result=state.expr||'0';save();render()}
function sci(k){const map={sin:'Math.sin(',cos:'Math.cos(',tan:'Math.tan(',asin:'Math.asin(',acos:'Math.acos(',atan:'Math.atan(', '√':'Math.sqrt(', 'x²':'**2','xʸ':'**','ln':'Math.log(',log:'Math.log10(',π:'Math.PI',e:'Math.E'};state.expr+=map[k]??k;state.result=state.expr;save();render()}
function sanitize(x){return x.replace(/[^0-9+\-*/%.(),\sA-Za-z_]/g,'').replace(/Math\.(sin|cos|tan|asin|acos|atan|sqrt|log10|log|PI|E)/g,'Math.$1')}
function calc(){try{let e=sanitize(state.expr);e=e.replace(/(\d+(?:\.\d+)?)%/g,'($1/100)');let r=Function('return ('+e+')')();if(!Number.isFinite(r))throw Error();r=String(Math.round((r+Number.EPSILON)*1e12)/1e12);state.result=r;state.history.unshift({e:state.expr,r});state.history=state.history.slice(0,100);save()}catch{state.result='Error'}}
function mem(m){const n=Number(state.result)||0;if(m==='MC')state.memory=0;if(m==='MR'){state.expr+=String(state.memory);state.result=state.expr}if(m==='M+')state.memory+=n;if(m==='M-')state.memory-=n;save();render()}
const units={length:{m:1,km:1000,cm:.01,mm:.001,ft:.3048,in:.0254,yd:.9144,mi:1609.344},weight:{kg:1,g:.001,mg:.000001,lb:.45359237,oz:.0283495231}};
function bindConverter(){let kind='length';const fu=$('#fromUnit'),tu=$('#toUnit'),fv=$('#fromVal');function fill(){const opts=Object.keys(units[kind]).map(u=>`<option>${u}</option>`).join('');fu.innerHTML=tu.innerHTML=opts;tu.selectedIndex=1;convert()}function convert(){const v=Number(fv.value)||0;const r=v*units[kind][fu.value]/units[kind][tu.value];$('#toVal').value=r;$('#convResult').textContent=`${v} ${fu.value} = ${r} ${tu.value}`}fill();fv.oninput=convert;fu.onchange=convert;tu.onchange=convert;$('#weightMode').onclick=()=>{kind='weight';$('#weightMode').classList.add('active');$('#lengthMode').classList.remove('active');fill()};$('#lengthMode').onclick=()=>{kind='length';$('#lengthMode').classList.add('active');$('#weightMode').classList.remove('active');fill()}}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
$('#clearAll').onclick=()=>{if(confirm('Clear all locally saved calculator data?')){localStorage.removeItem(KEY);location.reload()}};
function snow(){const el=document.createElement('span');el.className='snow';el.textContent='❄';el.style.left=Math.random()*100+'vw';el.style.setProperty('--drift',(Math.random()*160-80)+'px');el.style.animationDuration=(6+Math.random()*7)+'s';el.style.opacity=.35+Math.random()*.55;$('#snow').appendChild(el);setTimeout(()=>el.remove(),14000)}setInterval(snow,500);for(let i=0;i<8;i++)setTimeout(snow,i*250);render();
